package org.ekber.domain;

// Generated 13.Eki.2010 10:25:23 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * Comments generated by hbm2java
 */


public class Comments implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	
	private Integer commentid;
	private String commenttext;
	private String sender;
	private String senderIp;
	private String senderMail;
	private Date senddate;
	private Article articles;
	private boolean activated;
	private boolean admin;

	public Comments(Integer commentid, String commenttext, String sender,
			String senderIp, String senderMail, Date senddate,
			Article articles, boolean activated, boolean admin) {
		super();
		this.commentid = commentid;
		this.commenttext = commenttext;
		this.sender = sender;
		this.senderIp = senderIp;
		this.senderMail = senderMail;
		this.senddate = senddate;
		this.articles = articles;
		this.activated = activated;
		
		senddate = new Date();
	}
	
	public Comments() {
		super();
		senddate = new Date();
	}


	public Integer getCommentid() {
		return this.commentid;
	}

	public void setCommentid(Integer commentid) {
		this.commentid = commentid;
	}

	public String getCommenttext() {
		return this.commenttext;
	}

	public void setCommenttext(String commenttext) {
		this.commenttext = commenttext;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getSenderIp() {
		return senderIp;
	}

	public void setSenderIp(String senderIp) {
		this.senderIp = senderIp;
	}

	public String getSenderMail() {
		return senderMail;
	}

	public void setSenderMail(String senderMail) {
		this.senderMail = senderMail;
	}

	public Date getSenddate() {
		return this.senddate;
	}

	public void setSenddate(Date senddate) {
		this.senddate = senddate;
	}

	public Article getArticles() {
		return articles;
	}

	public void setArticles(Article articles) {
		this.articles = articles;
	}

	public boolean isActivated() {
		return activated;
	}

	public void setActivated(boolean activated) {
		this.activated = activated;
	}

	public boolean isAdmin() {
		return admin;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

	@Override
	public int hashCode() {
		int hash = 0;
		hash += (commentid != null ? commentid.hashCode() : 0);
		return hash;
	}

	@Override
	public boolean equals(Object object) {
		if (!(object instanceof Comments)) {
			return false;
		}
		Comments other = (Comments) object;
		if ((this.commentid == null && other.commentid != null)
				|| (this.commentid != null && !this.commentid
						.equals(other.commentid))) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Comments[id=" + commentid + "]";
	}
}
