package org.ekber.domain;

import java.util.Date;

// Generated 13.Eki.2010 10:25:23 by Hibernate Tools 3.3.0.GA

/**
 * Category generated by hbm2java
 */

public class UserRate implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer rateId;
	private Integer rate;
	private String raterIp;
	private Date ratedDate;
	private Article articlesrate;
	
	public UserRate(Integer rateId, Integer rate, String raterIp,
			Date ratedDate, Article articlesrate) {
		super();
		this.rateId = rateId;
		this.rate = rate;
		this.raterIp = raterIp;
		this.ratedDate = ratedDate;
		this.articlesrate = articlesrate;
	}
	
	public UserRate() {
		super();
	}
	
    public Integer getRateId() {
		return rateId;
	}

	public void setRateId(Integer rateId) {
		this.rateId = rateId;
	}

	public Integer getRate() {
		return rate;
	}

	public void setRate(Integer rate) {
		this.rate = rate;
	}

	public String getRaterIp() {
		return raterIp;
	}

	public void setRaterIp(String raterIp) {
		this.raterIp = raterIp;
	}

	public Date getRatedDate() {
		return ratedDate;
	}

	public void setRatedDate(Date ratedDate) {
		this.ratedDate = ratedDate;
	}

	public Article getArticlesrate() {
		return articlesrate;
	}

	public void setArticlesrate(Article articlesrate) {
		this.articlesrate = articlesrate;
	}

	@Override
    public int hashCode() {
        int hash = 0;
        hash += (rateId != null ? rateId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        if (!(object instanceof UserRate)) {
            return false;
        }
        UserRate other = (UserRate) object;
        if ((this.rateId == null && other.rateId != null) || (this.rateId != null && !this.rateId.equals(other.rateId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "UserRate[id=" + rateId + "]";
    }
}
